#+title: Note Silos and Sequential Notes
#+date: 2025-07-16T20:34:17-0400
#+type: publication
#+tags: [General]

* Introduction and Background
I have been preparing for starting my University journey this fall and with that comes +spring+ summer cleaning of my notes. This is something I kind of look for because it gives me an excuse to reevaluate my workflow for notes. I stay away from this during the school year, /typically/, but summer time is good for re-evaluating my workflows.

Something that was always confusing for me was the usecase for Denote's [[https://protesilaos.com/emacs/denote-sequence][sequence]] and [[https://protesilaos.com/emacs/denote-silo][silo]] features. I wanted to figure out a way that I could use them. And that is precisely what I achieved recently.

* How I Decided To Use Denote Silo Functionality
I have a lot of old notes from past classes that I have taken, but rarely reference. I still want to hold onto them. It just feels bad to throw away information that I have synthesized into a way that I understand. I may work on something related to the notes that I took, or take a class with similar topics (e.g. AP United States History notes will apply to an American History course more or less)

As such, I have created a silo for my old notes in ~~/Notes/Old Notes~ and they have a structure like this:

#+begin_src sh
  tree "~/Notes/Old Notes/" -d -L 2
  /home/bard/Notes/Old Notes/
  ├── Old Notes (2022-2023)
  ├── Old Notes (2023-2024)
  └── Old Notes (2024-2025)
  
  4 directories
#+end_src

** Not the most traditional method
Now I know that this isn't the way your really "supposed to do it". The traditional way (as far as Org Roam/denote) would suggest the user to put all of their notes in a single directory. But for me the Old Notes silo is an organizational barrier to /let go/  of my old notes. This not only removes the temptation to reorganize them to fit a new note taking convention that I have taken up, but also de-clutters my current working notes directory from quasi-irrelevant ones.

* How I Decided To Use Denote Sequence Functionality
NOTE: For the longest time I thought this was the most useless thing ever (no offence. Personally, I just didn't get it [until now!])
** How howm Inspired Me To Take Another Look
It was today (date of writing) that I finally figured out how anyone could make sense of a possible use case for this. This surprised me, especially as someone who has loosely "studied" note-taking and organization for about 3 years through YouTube content and blog posts. This insight came up as a random thought that popped up when I was taking an n-th look at [[https://github.com/kaorahi/howm/][howm]]. I think the home page and it's minimal approach to linking between files was the main drawing factor, but at the end of the day I have a system that already works for me.

I had recently (in the past year or so) taken up interest in it again because of [[https://www.youtube.com/watch?v=o1x_UM0HDhE][a video by qnnnp]], aka Андрей Суховский, that details his /zettlekasten-esque/ workflow using this tool. I think that this video is an awesome introduction to an efficient system of note taking in Emacs. He uses a basically default Emacs which I can say is just as cool to me as someone with a [[https://tecosaur.github.io/emacs-config/config.pdf][super riced out Emacs system like tecosaur]] (a 317 page pdf 💀).

Суховский comes at it with the approach of a Картотека system (zettlekasten). He makes physical card notes and then transfers them into the indexing system. There's something about the simplicity of this (not that my system is complicated) that is satisfying.

This video got me thinking again about how my system currently works. And I arrived a this conclusion:

** The "New?" System
Basically when I create a note, a simple process happens:

1. Create a note (with denote prompts like title and keywords)
2. Then I think about how it could relate to a possible topic that I have written about before
   a. Link if necessary
3. Write the note

*** How does this relate to sequence
Well that's a good question. The sequence can lie in the second step. I have been organizing notes with their topical /meta-note/ using [[https://protesilaos.com/emacs/denote-org][denote-org's]] dynamic block automatic linking. But I have realized that a better way of doing this is by trying to incorporate the notes into a possible sequence. As I discover more about a topic I can do this:

#+begin_src
20250716T201152==1--tea-research__research.org
20250123T053843==1=1--effects-of-roasted-green-tea-on-human-responses__research.org
20250313T191558==1=2--green-tea-consumption-and-cognitive-function__research.org
20250313T203914==1=3--green-tea-enhances-parieto-frontal-connectivity__research.org
20250313T213601==1=4--the-cognitive-benefits-of-
   green-tea-the-neural-and-behavioral-effects__research_writing.org
#+end_src

=Now what is this?=

I was doing a research paper project in English class last school year (really just a few months ago). I was researching green tea because it's something I enjoy. I wrote some annotated bibliographies for sources because it was a requirement for the project. I found today that the above format is the best way to organize them. 

It all starts with the first not at the top, it's the beginning of the sequence (parent). It has the signature of ~==1~ which is a "top-level" signature. If I decide to have another sequenced topic, it will start with a ~==2~.

The subsequent notes underneath are children of this main topic of tea research.

So it's better visualized like this:
#+begin_src 
==1__green-tea-cognition
├── ==1_1__roasted-green-tea-human-responses
├── ==1=2__consumption-and-cognition
├── ==1=3__parieto-frontal-connectivity
├── ==1=4__cognitive-benefits-paper
#+end_src
